version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: lingulu_postgres_core
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lingulu
    ports:
      - "5432:5432"
    volumes:
      - postgres_core_data:/var/lib/postgresql/data
    networks:
      - spring-network

  redis:
    image: redis:7
    container_name: lingulu_redis_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_cache_data:/data
    networks:
      - spring-network
  mongo:
    image: mongo:6
    container_name: lingulu_mongo_nosql
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_chat_data:/data/db
    networks:
      - spring-network

networks:
  spring-network:

volumes:
  postgres_data:
  redis_data:
  mongo_data: